In [1]:
import numpy as np


In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

### Implementation Of MAE

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)


Total error is: 2.5
Mean absolute error is: 0.5


0.5

#### Alternative way using numpy

In [5]:
np.abs(y_predicted-y_true)


array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_true))


0.5

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [8]:
mae_np(y_predicted, y_true)

0.5

### Implementing Log Loss (Binary Cross Entropy)

In [9]:
np.log([0])


/var/folders/r_/3qrs8_t92fl992f55y6b6pkc0000gn/T/ipykernel_96341/348854998.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([1e-15])


array([-34.53877639])

In [12]:
y_predicted


array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
1-epsilon

0.999999999999999

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]